import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import { WorksheetItem } from '../../types';

// Register Helvetica (built-in standard font)
// We use Helvetica so it works perfectly offline and avoids CORS issues.

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    padding: 40,
    fontFamily: 'Helvetica',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    borderBottomWidth: 2,
    borderBottomColor: '#f97316',
    paddingBottom: 10,
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1f2937',
  },
  subtitle: {
    fontSize: 10,
    color: '#f97316',
    marginTop: 4,
  },
  studentInfo: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  infoLine: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  infoLabel: {
    fontSize: 10,
    color: '#6b7280',
    marginRight: 4,
  },
  infoBlank: {
    width: 120,
    borderBottomWidth: 1,
    borderBottomColor: '#d1d5db',
  },
  questionBlock: {
    marginBottom: 25,
    padding: 10,
  },
  questionHeader: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  questionNumber: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#f97316',
    marginRight: 8,
  },
  questionText: {
    fontSize: 12,
    color: '#1f2937',
    flex: 1,
    lineHeight: 1.5,
  },
  writingSpace: {
    height: 40,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderStyle: 'dashed',
    borderRadius: 4,
    marginTop: 10,
    backgroundColor: '#fafafa',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#9ca3af',
    fontSize: 10,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 10,
  },
});

interface WorksheetPDFProps {
  items: WorksheetItem[];
}

export const WorksheetPDF: React.FC<WorksheetPDFProps> = ({ items }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <View>
          <Text style={styles.title}>Practice Sheet</Text>
          <Text style={styles.subtitle}>Generated by Chekki AI</Text>
        </View>
        <View style={styles.studentInfo}>
          <View style={styles.infoLine}>
            <Text style={styles.infoLabel}>Name:</Text>
            <View style={styles.infoBlank} />
          </View>
          <View style={styles.infoLine}>
            <Text style={styles.infoLabel}>Date:</Text>
            <View style={styles.infoBlank} />
          </View>
        </View>
      </View>

      <View style={{ flex: 1 }}>
        {items.map((item, index) => (
          <View key={item.id} style={styles.questionBlock} wrap={false}>
            <View style={styles.questionHeader}>
              <Text style={styles.questionNumber}>{index + 1}.</Text>
              <Text style={styles.questionText}>{item.question_text}</Text>
            </View>
            <View style={styles.writingSpace} />
          </View>
        ))}
      </View>

      <Text style={styles.footer} render={({ pageNumber, totalPages }) => (
        `Page ${pageNumber} of ${totalPages} - Chekki AI Practice Worksheets`
      )} fixed />
    </Page>
  </Document>
);
