
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    app_name: "Chekki AI",
    tagline: "Mom's Homework Helper",
    login: "Log In",
    logout: "Sign Out",
    scans: "Scans",
    pro_plan: "Pro Plan 🚀",
    
    // Hero / Camera
    hero_greeting: "👋 Hi! I'm Chekki.",
    hero_desc: "Your supportive partner for home learning. Chekki checks the work so you can focus on the praise!",
    hero_badge: "AI Smart Assistant",
    hero_cta_title: "Ready to get started?",
    hero_cta_desc: "Join thousands of parents using Chekki to make homework time happier and more encouraging.",
    hero_cta_btn: "Start for Free",
    
    drop_title: "Drop homework here",
    drop_subtitle: "or tap to select from album",
    processing: "Chekki is looking...",
    checking: "Checking carefully...",
    
    // Dashboard (Logged In)
    dash_welcome: "Hello,",
    dash_subtitle: "Let's make homework fun! I'm here to assist you.",
    scans_left: "Scans Left",
    supported_formats: "Supported formats: JPG, PNG, WEBP, HEIC • Max size: 10MB",

    // Splash
    splash_subtitle: "Mom's Homework Partner",

    // Onboarding
    onb_1_title: "I'll help check the work!",
    onb_1_desc: "So you can focus on the praise.",
    onb_1_btn: "Get Started",
    onb_2_title: "I need eyes to see.",
    onb_2_desc: "Please allow camera access so I can help.",
    onb_2_btn: "Enable Camera",
    onb_3_title: "Shall I notify you?",
    onb_3_desc: "I'll let you know when the review is ready.",
    onb_3_btn: "Yes, notify me!",

    // Features
    feat_vision_title: "Instant Vision",
    feat_vision_desc: "Chekki sees what you see, understanding handwriting and context to offer the best support.",
    feat_grading: "3s Auto-Check",
    feat_korean: "Korean Explanations",
    feat_audio: "Native Audio",
    feat_audio_desc: "Hear the correct pronunciation instantly to guide your child with confidence.",
    feat_tips: "Praise Guide",
    feat_review_desc: "Help your child learn from mistakes gently. We compile them for a stress-free review later.",
    feat_privacy: "Privacy First",
    feat_privacy_desc: "We process images instantly and never store them. Your child's homework stays private on your device.",

    // Stats
    stat_accuracy: "Accuracy",
    stat_users: "Happy Moms",
    stat_questions: "Questions Helped",
    stat_rating: "App Rating",

    // Loading Steps (NEW)
    loading_step1: "Looking at the wonderful handwriting...",
    loading_step2: "Reviewing the answers gently...",
    loading_step3: "Preparing praise tips for you...",
    loading_step4: "Almost ready for you...",
    scan_loading_text: "SCANNING...",
    growing_text: "Growing!",

    // Error
    error_title: "Let's try that again!",
    error_desc: "I'm having a little trouble seeing the photo clearly. Could you take it again for me?",
    btn_retake: "Retake Photo",

    // Workspace
    ws_overlay: "Focus View",
    ws_list: "Split View",
    ws_scan_again: "Chekki! (Scan Again)",
    ws_summary_title: "Chekki's Summary",
    ws_ref_scan: "Original Scan",
    ws_read_only: "Read-only",
    ws_results_title: "Chekki's Results",
    ws_items_found: "items found",
    ws_repeated: "Repeated",
    ws_times: "times",
    ws_review_tip: "Tip: Click the flag 🚩 to gently save tricky questions for later practice!",

    // Paywall
    pw_title: "Upgrade to Pro",
    pw_desc: "Unlock unlimited help for your child.",
    pw_free_title: "Free Plan",
    pw_free_limit: "3 Scans / Month",
    pw_current: "Current",
    pw_pro_title: "Pro Plan",
    pw_pro_limit: "Unlimited Scans, AI Practice Sheets, Native Audio & Pronunciation Check",
    pw_rec: "RECOMMENDED",
    pw_price: "$9.99/mo",
    pw_btn: "Upgrade Now (Mock)",
    pw_footer: "Secured by MockBilling™. No credit card required for demo.",

    // Review (O-dap)
    review_title: "Review Note",
    review_empty_title: "No mistakes saved yet",
    review_empty_desc: "If you see a tricky question, click the 'Flag' icon 🚩. We can practice it together later!",
    review_print_btn: "Print Review Sheet (PDF)",
    lbl_mistakes_count: "questions to review",
    lbl_correct_answer: "Correct Answer:",
    lbl_question: "Question",
    lbl_write_answer: "Let's try writing it here:",
    lbl_mom_tip: "Parent's Encouragement:",
    print_footer: "Generated by Chekki AI - Growing every day!",

    footer_text: "Powered by Google Gemini 2.5 • Built with ❤️ for Parents"
  },
  ko: {
    app_name: "채키 AI",
    tagline: "엄마표 영어 숙제 채점 & 티칭",
    login: "로그인",
    logout: "로그아웃",
    scans: "회 스캔",
    pro_plan: "프로 플랜 🚀",

    // Hero / Camera
    hero_greeting: "👋 안녕하세요! 든든한 숙제 친구 채키예요.",
    hero_desc: "엄마표 영어 교육의 따뜻한 파트너. 채키가 채점을 도와드릴 테니, 엄마는 칭찬만 해주세요!",
    hero_badge: "AI 스마트 어시스턴트",
    hero_cta_title: "함께 시작해볼까요?",
    hero_cta_desc: "숙제 시간이 즐거워지는 마법! 수천 명의 부모님과 함께해요.",
    hero_cta_btn: "무료로 시작하기",

    drop_title: "숙제를 여기에 놓아주세요",
    drop_subtitle: "또는 터치해서 앨범에서 선택하기",
    processing: "채키가 살펴보고 있어요...",
    checking: "꼼꼼히 확인 중...",

    // Dashboard (Logged In)
    dash_welcome: "반가워요,",
    dash_subtitle: "오늘 숙제도 채키와 함께해요! 제가 도와드릴게요.",
    scans_left: "남은 스캔",
    supported_formats: "지원 형식: JPG, PNG, WEBP, HEIC • 최대 크기: 10MB",

    // Splash
    splash_subtitle: "엄마표 영어 숙제 파트너",

    // Onboarding
    onb_1_title: "채점은 제가 도와드릴게요!",
    onb_1_desc: "엄마는 아이에게 칭찬만 해주세요.",
    onb_1_btn: "시작하기",
    onb_2_title: "숙제를 보려면 눈이 필요해요.",
    onb_2_desc: "제가 잘 볼 수 있게 카메라 권한을 주세요.",
    onb_2_btn: "카메라 켜기",
    onb_3_title: "다 되면 알려드릴까요?",
    onb_3_desc: "검토가 끝나면 살짝 알려드릴게요.",
    onb_3_btn: "네, 알려주세요!",

    // Features
    feat_vision_title: "AI 비전 (Instant Vision)",
    feat_vision_desc: "채키가 아이의 손글씨와 문맥을 이해하여, 가장 알맞은 학습 가이드를 제공합니다.",
    feat_grading: "3초 자동 확인",
    feat_korean: "친절한 한국어 설명",
    feat_audio: "원어민 발음 듣기",
    feat_audio_desc: "자신 있게 지도하실 수 있도록, 원어민 발음을 바로 들려드려요.",
    feat_tips: "엄마표 칭찬 가이드",
    feat_review_desc: "아이가 실수로부터 부드럽게 배울 수 있도록 도와주세요. 스트레스 없이 복습할 수 있게 오답노트를 자동으로 정리해 드립니다.",
    feat_privacy: "안심 프라이버시",
    feat_privacy_desc: "이미지는 분석 후 즉시 삭제됩니다. 우리 아이의 소중한 숙제, 서버에 남기지 않고 안전하게 관리하세요.",

    // Stats
    stat_accuracy: "정확도",
    stat_users: "함께하는 부모님",
    stat_questions: "검토한 문제",
    stat_rating: "앱 평점",

    // Loading Steps (NEW)
    loading_step1: "글씨를 꼼꼼히 살펴보고 있어요...",
    loading_step2: "정답을 확인하는 중이에요...",
    loading_step3: "아이에게 해줄 칭찬을 찾고 있어요...",
    loading_step4: "거의 다 됐어요!",
    scan_loading_text: "스캔 중...",
    growing_text: "성장 중!",
    
    // Error
    error_title: "조금만 더 잘 보여주세요!",
    error_desc: "사진이 약간 흐릿해서 잘 안 보여요. 다시 한 번 예쁘게 찍어주실 수 있나요?",
    btn_retake: "다시 찍기",

    // Workspace
    ws_overlay: "포커스 뷰",
    ws_list: "분할 보기",
    ws_scan_again: "채키! (다시 찍기)",
    ws_summary_title: "채키의 한줄 요약",
    ws_ref_scan: "원본 숙제",
    ws_read_only: "보기 전용",
    ws_results_title: "채키의 검토 결과",
    ws_items_found: "개 발견",
    ws_repeated: "반복",
    ws_times: "회",
    ws_review_tip: "팁: 깃발 🚩을 눌러 어려운 문제를 저장해두면 나중에 같이 볼 수 있어요!",

    // Paywall
    pw_title: "프로 플랜으로 더 든든하게",
    pw_desc: "우리 아이를 위한 무제한 학습 도우미.",
    pw_free_title: "무료 플랜",
    pw_free_limit: "월 3회 스캔",
    pw_current: "현재 이용중",
    pw_pro_title: "프로 플랜",
    pw_pro_limit: "무제한 스캔, AI 연습문제 생성, 원어민 발음 확인 & 발음 체크",
    pw_rec: "추천",
    pw_price: "월 9,900원",
    pw_btn: "지금 업그레이드 (테스트)",
    pw_footer: "데모 버전입니다. 실제 결제되지 않습니다.",

    // Review (O-dap)
    review_title: "오답 노트 (Review Note)",
    review_empty_title: "아직 저장된 문제가 없어요",
    review_empty_desc: "아이가 어려워하는 문제가 있나요? '깃발' 아이콘 🚩을 눌러주세요. 나중에 다시 연습할 수 있어요!",
    review_print_btn: "PDF 복습 시트 만들기 (Print)",
    lbl_mistakes_count: "개의 복습 문제",
    lbl_correct_answer: "정답:",
    lbl_question: "질문",
    lbl_write_answer: "여기에 다시 써볼까요?",
    lbl_mom_tip: "부모님을 위한 칭찬 팁:",
    print_footer: "채키 AI가 만든 복습 노트 - 매일매일 자라나요!",

    footer_text: "Powered by Google Gemini 2.5 • Built with ❤️ for Parents"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Initialize lazily to prevent flicker/revert on reload
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem('hw_language');
      if (stored === 'en' || stored === 'ko') {
        return stored;
      }
    }
    return 'ko'; // Default
  });

  // Persist to storage
  useEffect(() => {
    localStorage.setItem('hw_language', language);
  }, [language]);

  const t = (key: string) => {
    // @ts-ignore
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
