import { useState, useRef } from 'react';
import { doc, getDoc, setDoc } from 'firebase/firestore';
import { dbInstance, auth } from '../services/database';
import { compressImage, stripDataUrlPrefix, getMimeTypeFromDataUrl } from '../services/compressImage';
import { asString, asJoinedString } from '../utils/validate';
import { parseApiError } from '../utils/describeError';
import { validateCurriculumOtherField } from '../src/utils/curriculumGuardrail';
import type { UserProfile } from '../types';
import type { useToast } from '../contexts/ToastContext';

type ShowToast = ReturnType<typeof useToast>['showToast'];

// Owns the curriculum/scan editor "bucket" — everything behind the
// Syllabus/Homework tabs (topic/vocab/phonics/passage/answer key, the
// syllabus+worksheet scan pipeline, and the scanned-doc picker state).
// Extracted from TeacherPage (Phase 1 of the incremental split — see
// buzzing-nibbling-hearth plan) because it was the cleanest, most
// role-exclusive contiguous state block in that file. A few derived values
// (curriculumTopic/Vocab/Phonics/Passage/Other, curriculumSlideIndex) are
// also consumed outside the curriculum tab (NativeDirectorPortal,
// NativeFtDashboard), so this hook returns them alongside the setters those
// other consumers still need.
export function useCurriculumEditorState(
  selectedClass: any,
  fallbackDemoClass: any,
  user: UserProfile | null,
  showToast: ShowToast,
  isKo: boolean,
  uploadMode: 'syllabus' | 'worksheet',
  setUploadMode: (mode: 'syllabus' | 'worksheet') => void,
  setSyncWarning: (msg: string | null) => void,
) {
  const [selectedTextbookName, setSelectedTextbookName] = useState<string>('');
  const [curriculumTopic, setCurriculumTopic] = useState('');
  const [curriculumVocab, setCurriculumVocab] = useState('');
  const [curriculumPhonics, setCurriculumPhonics] = useState('');
  const [curriculumPassage, setCurriculumPassage] = useState('');
  const [curriculumOther, setCurriculumOther] = useState('');
  // The literal answer key extracted from a worksheet scan (question/answer
  // pairs), scoped to this same week's curriculum doc — separate from
  // vocab/phonics/passage above because it's only ever produced by a
  // worksheet scan (never a syllabus scan) and was previously generated by
  // the AI and silently discarded (never saved, never used at grading time).
  const [curriculumAnswerKey, setCurriculumAnswerKey] = useState<Array<{ questionText: string; answer: string }>>([]);
  const [curriculumLastEditedByName, setCurriculumLastEditedByName] = useState('');
  const [curriculumLastEditedAt, setCurriculumLastEditedAt] = useState('');
  const [curriculumSlideIndex, setCurriculumSlideIndex] = useState(0);
  const [isLoadingCurriculum, setIsLoadingCurriculum] = useState(false);
  // loadCurriculum captures `targetClass` by closure at call time with no
  // cancellation — switching selectedClass while a fetch is still in flight
  // used to let the older, now-stale response's setters land after the
  // newer class's own load, silently overwriting the just-selected class's
  // curriculum fields with the previous class's data. This ref tracks which
  // request is the most recent one so a superseded response can be dropped.
  const latestCurriculumRequestId = useRef<string | null>(null);
  const [isSavingCurriculum, setIsSavingCurriculum] = useState(false);
  const [isGeneratingWorksheet, setIsGeneratingWorksheet] = useState(false);
  const [isDraggingFile, setIsDraggingFile] = useState(false);
  const [isScanningTextbook, setIsScanningTextbook] = useState(false);
  const [textbookPreviewUrl, setTextbookPreviewUrl] = useState<string | null>(null);

  // Scanned AI Worksheet Modal & Selection state
  const [showScannedModal, setShowScannedModal] = useState(false);
  const [scannedData, setScannedData] = useState<any>(null);
  const [uploadedFileType, setUploadedFileType] = useState<'image' | 'pdf'>('image');
  const [uploadedFileName, setUploadedFileName] = useState<string>('');
  const [textbookPreviewUrls, setTextbookPreviewUrls] = useState<string[]>([]);
  const [selectedPageIndex, setSelectedPageIndex] = useState<number | 'all'>('all');

  // Staged pages picked but not yet scanned — lets teachers add/remove
  // individual page photos before committing to a scan, instead of the
  // previous all-or-nothing behavior where every file select immediately
  // replaced the whole batch and re-scanned (Audit: no way to add or
  // delete images after uploading).
  const [pendingScanFiles, setPendingScanFiles] = useState<{ file: File; previewUrl: string }[]>([]);

  const handleStageFiles = (inputFiles: FileList | File[], scanType: 'syllabus' | 'worksheet') => {
    setUploadMode(scanType);
    const files = inputFiles instanceof FileList ? Array.from(inputFiles) : inputFiles;
    setPendingScanFiles((prev) => {
      const combined = [...prev, ...files.map((file) => ({ file, previewUrl: URL.createObjectURL(file) }))];
      return combined.slice(0, 5);
    });
  };

  const handleRemoveStagedFile = (index: number) => {
    setPendingScanFiles((prev) => {
      const target = prev[index];
      if (target) URL.revokeObjectURL(target.previewUrl);
      return prev.filter((_, i) => i !== index);
    });
  };

  const clearStagedFiles = () => {
    setPendingScanFiles((prev) => {
      prev.forEach((p) => URL.revokeObjectURL(p.previewUrl));
      return [];
    });
  };

  const handleScanStagedFiles = (scanType: 'syllabus' | 'worksheet') => {
    if (pendingScanFiles.length === 0) return;
    void handleTextbookFileUpload(pendingScanFiles.map((p) => p.file), scanType);
  };

  // Separate Syllabus Upload State
  const [syllabusFileName, setSyllabusFileName] = useState<string>('');
  const [syllabusPreviewUrl, setSyllabusPreviewUrl] = useState<string | null>(null);
  const [syllabusScannedData, setSyllabusScannedData] = useState<any>(null);
  const [syllabusWeeks, setSyllabusWeeks] = useState<number>(4);
  const [isScanningSyllabus, setIsScanningSyllabus] = useState(false);
  const [syllabusWeeklySchedule, setSyllabusWeeklySchedule] = useState<Array<{ week: number; topic: string; vocab: string; phonics: string }>>([]);

  // Separate Worksheet Upload State
  const [worksheetFileName, setWorksheetFileName] = useState<string>('');
  const [worksheetPreviewUrl, setWorksheetPreviewUrl] = useState<string | null>(null);
  const [worksheetScannedData, setWorksheetScannedData] = useState<any>(null);
  const [isScanningWorksheet, setIsScanningWorksheet] = useState(false);
  const [activeScannedModalType, setActiveScannedModalType] = useState<'syllabus' | 'worksheet'>('syllabus');

  const handleSyllabusWeeksChange = (weeks: number) => {
    const safeWeeks = Math.max(1, Math.min(24, weeks));
    setSyllabusWeeks(safeWeeks);
    setSyllabusWeeklySchedule(prev => {
      const next = [...prev];
      if (next.length < safeWeeks) {
        for (let i = next.length + 1; i <= safeWeeks; i++) {
          next.push({
            week: i,
            topic: `Unit ${i}: Topic Title`,
            vocab: `target_word_1, target_word_2, target_word_3`,
            phonics: `phonics_rule_${i}`
          });
        }
      } else {
        return next.slice(0, safeWeeks);
      }
      return next;
    });
  };

  // Pick & Choose Selection State inside Scanned AI Modal
  const [selectedScannedTopic, setSelectedScannedTopic] = useState(true);
  const [selectedScannedPassage, setSelectedScannedPassage] = useState(true);
  const [selectedScannedOther, setSelectedScannedOther] = useState(true);
  const [selectedScannedVocab, setSelectedScannedVocab] = useState<string[]>([]);
  const [selectedScannedPhonics, setSelectedScannedPhonics] = useState<string[]>([]);
  const [activeScannedTab, setActiveScannedTab] = useState<'parentView' | 'picker'>('picker');
  const [scanStatusMessage, setScanStatusMessage] = useState<string | null>(null);
  const [showDocPreviewModal, setShowDocPreviewModal] = useState(false);
  const [docPreviewUrl, setDocPreviewUrl] = useState<string | null>(null);

  // New Chip Input state
  const [newVocabInput, setNewVocabInput] = useState('');
  const [newPhonicsInput, setNewPhonicsInput] = useState('');

  // Vocab Chip helpers
  const handleAddVocabWord = (wordToAdd?: string) => {
    const word = (wordToAdd !== undefined ? wordToAdd : newVocabInput).trim();
    if (!word) return;
    const currentList = curriculumVocab.split(/[,\n]/).map(s => s.trim()).filter(Boolean);
    if (!currentList.map(w => w.toLowerCase()).includes(word.toLowerCase())) {
      const updated = [...currentList, word];
      setCurriculumVocab(updated.join(', '));
    }
    if (wordToAdd === undefined) setNewVocabInput('');
  };

  const handleRemoveVocabWord = (indexToRemove: number) => {
    const currentList = curriculumVocab.split(/[,\n]/).map(s => s.trim()).filter(Boolean);
    const updated = currentList.filter((_, idx) => idx !== indexToRemove);
    setCurriculumVocab(updated.join(', '));
  };

  // Phonics Chip helpers
  const handleAddPhonicsRule = (ruleToAdd?: string) => {
    const rule = (ruleToAdd !== undefined ? ruleToAdd : newPhonicsInput).trim();
    if (!rule) return;
    const currentList = curriculumPhonics.split(/[,\n]/).map(s => s.trim()).filter(Boolean);
    if (!currentList.map(r => r.toLowerCase()).includes(rule.toLowerCase())) {
      const updated = [...currentList, rule];
      setCurriculumPhonics(updated.join(', '));
    }
    if (ruleToAdd === undefined) setNewPhonicsInput('');
  };

  const handleRemovePhonicsRule = (indexToRemove: number) => {
    const currentList = curriculumPhonics.split(/[,\n]/).map(s => s.trim()).filter(Boolean);
    const updated = currentList.filter((_, idx) => idx !== indexToRemove);
    setCurriculumPhonics(updated.join(', '));
  };

  const handleRemoveAnswerKeyEntry = (indexToRemove: number) => {
    setCurriculumAnswerKey((prev) => prev.filter((_, idx) => idx !== indexToRemove));
  };

  const handleEditAnswerKeyEntry = (index: number, field: 'questionText' | 'answer', value: string) => {
    setCurriculumAnswerKey((prev) => prev.map((entry, idx) => idx === index ? { ...entry, [field]: value } : entry));
  };

  const handleTextbookFileUpload = async (inputFiles: FileList | File[] | File, scanType: 'syllabus' | 'worksheet' = uploadMode) => {
    const fileList: File[] = inputFiles instanceof FileList
      ? Array.from(inputFiles)
      : Array.isArray(inputFiles)
        ? inputFiles
        : [inputFiles];

    if (!fileList || fileList.length === 0) return;

    // Cap at 5 files max per scan batch
    const selectedFiles = fileList.slice(0, 5);

    // The backend (api/analyze.ts) hard-caps the request body at 10MB, and
    // base64 encoding inflates raw file bytes by ~33% on top of that. This
    // must block (not just warn) and check the COMBINED batch size, not each
    // file individually — a previous 15MB-per-file, warning-only check let
    // real PDFs (and multi-file batches) sail past it and fail server-side
    // with a generic "couldn't read this file" message that gave no reason.
    const totalBytes = selectedFiles.reduce((sum, f) => sum + f.size, 0);
    const SAFE_RAW_BYTES_LIMIT = 6 * 1024 * 1024; // leaves room for base64 (+33%) + JSON envelope under the 10MB server cap
    if (totalBytes > SAFE_RAW_BYTES_LIMIT) {
      showToast({ type: 'error', message: isKo
        ? `⚠️ 파일 용량이 너무 큽니다 (${(totalBytes / (1024 * 1024)).toFixed(1)}MB, 최대 6MB). 단원별로 나누거나 페이지 수를 줄여 다시 시도해 주세요.`
        : `⚠️ File too large (${(totalBytes / (1024 * 1024)).toFixed(1)}MB combined, 6MB max). Split into smaller sections or fewer pages and try again.`
      });
      return;
    }

    if (scanType === 'syllabus') {
      setIsScanningSyllabus(true);
    } else {
      setIsScanningWorksheet(true);
    }

    setIsScanningTextbook(true);
    setScanStatusMessage(null);
    setSelectedPageIndex('all');

    const firstFile = selectedFiles[0];
    const isPdf = firstFile.type === 'application/pdf' || firstFile.name.toLowerCase().endsWith('.pdf');
    const fileName = selectedFiles.length === 1
      ? firstFile.name
      : (isKo ? `${firstFile.name} 외 ${selectedFiles.length - 1}개 파일` : `${firstFile.name} + ${selectedFiles.length - 1} more`);

    if (scanType === 'syllabus') {
      setSyllabusFileName(fileName);
    } else {
      setWorksheetFileName(fileName);
    }

    setUploadedFileType(isPdf ? 'pdf' : 'image');
    setUploadedFileName(fileName);

    try {
      const cleanBase64List: string[] = [];
      const previewList: string[] = [];

      for (const file of selectedFiles) {
        const reader = new FileReader();
        const base64Promise = new Promise<string>((resolve, reject) => {
          reader.onload = () => resolve(reader.result as string);
          reader.onerror = (err) => reject(err);
        });
        reader.readAsDataURL(file);
        const rawBase64Url = await base64Promise;

        if (!isPdf) {
          const compressed = await compressImage(rawBase64Url);
          previewList.push(compressed);
          cleanBase64List.push(stripDataUrlPrefix(compressed));
        } else {
          cleanBase64List.push(stripDataUrlPrefix(rawBase64Url));
        }
      }

      setTextbookPreviewUrls(previewList);
      const mainPreview = previewList.length > 0 ? previewList[0] : null;
      setTextbookPreviewUrl(mainPreview);

      if (scanType === 'syllabus') {
        setSyllabusPreviewUrl(mainPreview);
      } else {
        setWorksheetPreviewUrl(mainPreview);
      }

      // Call AI analysis with images_base64 list
      const idToken = await auth.currentUser?.getIdToken();
      const res = await fetch('/api/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${idToken}` },
        body: JSON.stringify({
          images_base64: cleanBase64List,
          mode: scanType === 'syllabus' ? 'syllabus_course_plan' : 'textbook_curriculum_ocr',
          mimeType: isPdf ? 'application/pdf' : getMimeTypeFromDataUrl(mainPreview || '')
        }),
      });

      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw parseApiError(res, data);

      if (data.analysis) {
        const analysisData = {
          ...data.analysis,
          scanType
        };
        setScannedData(analysisData);

        if (scanType === 'syllabus') {
          setSyllabusScannedData(analysisData);
        } else {
          setWorksheetScannedData(analysisData);
        }

        const words = Array.isArray(data.analysis.vocabWords)
          ? data.analysis.vocabWords
          : (data.analysis.vocabWords || '').split(/[,\n]/).map((s: string) => s.trim()).filter(Boolean);
        setSelectedScannedVocab(words);

        const sounds = Array.isArray(data.analysis.phonicsRules)
          ? data.analysis.phonicsRules
          : (data.analysis.phonicsRules || '').split(/[,\n]/).map((s: string) => s.trim()).filter(Boolean);
        setSelectedScannedPhonics(sounds);

        setSelectedScannedTopic(Boolean(data.analysis.topic));
        setSelectedScannedPassage(Boolean(data.analysis.passage));
        setSelectedScannedOther(Boolean(data.analysis.other));

        // Curriculum state is only written on explicit confirmation, via
        // applyScannedSelectionToCurriculum (fired by the review modal's
        // "Apply Selected to Curriculum" button) — this used to also write
        // straight into curriculumTopic/Vocab/Phonics/Passage right here,
        // before the teacher had even seen the review modal, so scanning
        // silently committed AI-extracted content with no chance to check
        // or edit it first (the modal that opened right after LOOKED like a
        // review step but the data was already applied).

        setActiveScannedModalType(scanType);
        setActiveScannedTab(scanType === 'syllabus' ? 'picker' : 'parentView');
        setShowScannedModal(true);
        setScanStatusMessage(
          isKo
            ? (scanType === 'syllabus' ? `📘 교재 목차 분석 완료! 주간 커리큘럼 단어 & 파닉스 범위가 추출되었습니다.` : `📄 일간 워크시트 스캔 완료! 학부모용 정답지 가이드가 추출되었습니다.`)
            : (scanType === 'syllabus' ? `📘 Course Syllabus scanned! Scope & Vocabulary extracted.` : `📄 Daily Worksheet scanned! Parent answer keys extracted.`)
        );
        clearStagedFiles();
      }
    } catch (err) {
      console.error('Curriculum scan failed:', err);
      // Clear the optimistic file-name/preview state set before the scan started —
      // otherwise a failed file stays listed as if it were successfully stored,
      // with only a transient toast (which disappears) explaining why.
      setUploadedFileName('');
      setTextbookPreviewUrl(null);
      setTextbookPreviewUrls([]);
      if (scanType === 'syllabus') {
        setSyllabusFileName('');
        setSyllabusPreviewUrl(null);
      } else {
        setWorksheetFileName('');
        setWorksheetPreviewUrl(null);
      }
      const detail = err instanceof Error && err.message && err.message !== 'Failed to fetch' ? ` (${err.message})` : '';
      showToast({
        type: 'error',
        message: isKo
          ? `스캔에 실패했습니다. 이미지를 확인하고 다시 시도해 주세요.${detail}`
          : `Scan failed — couldn't read this file. Please check the image and try again.${detail}`,
      });
    } finally {
      setIsScanningTextbook(false);
      setIsScanningSyllabus(false);
      setIsScanningWorksheet(false);
    }
  };

  const applyScannedSelectionToCurriculum = () => {
    if (!scannedData) return;
    if (selectedScannedTopic && scannedData.topic) {
      setCurriculumTopic(asString(scannedData.topic, String(scannedData.topic)));
    }
    // Merge into whatever's already there rather than replace — a syllabus
    // scan (term-level word list) and a worksheet scan (this week's words)
    // used to silently overwrite each other since both wrote the same plain
    // text field; applying either one now only adds words, never drops the
    // other source's.
    if (selectedScannedVocab.length > 0) {
      const existing = curriculumVocab.split(/[,\n]/).map(s => s.trim()).filter(Boolean);
      setCurriculumVocab(Array.from(new Set([...existing, ...selectedScannedVocab])).join(', '));
    }
    if (selectedScannedPhonics.length > 0) {
      const existing = curriculumPhonics.split(/[,\n]/).map(s => s.trim()).filter(Boolean);
      setCurriculumPhonics(Array.from(new Set([...existing, ...selectedScannedPhonics])).join(', '));
    }
    if (selectedScannedPassage && scannedData.passage) {
      setCurriculumPassage(asString(scannedData.passage, String(scannedData.passage)));
    }
    if (selectedScannedOther && scannedData.other) {
      setCurriculumOther(asString(scannedData.other, String(scannedData.other)));
    }
    // Worksheet scans (not syllabus scans) produce a real answer key —
    // previously extracted by the AI and then thrown away entirely (never
    // saved, never used at grading time). Merge by question text so
    // re-scanning the same worksheet doesn't create duplicate entries.
    if (Array.isArray(scannedData.detectedAnswers) && scannedData.detectedAnswers.length > 0) {
      const newEntries = scannedData.detectedAnswers
        .filter((a: any) => a?.questionText && a?.answer)
        .map((a: any) => ({ questionText: String(a.questionText), answer: String(a.answer) }));
      setCurriculumAnswerKey((prev) => {
        const existingTexts = new Set(prev.map((e: { questionText: string }) => e.questionText));
        return [...prev, ...newEntries.filter((e: { questionText: string }) => !existingTexts.has(e.questionText))];
      });
    }
    setShowScannedModal(false);
    setScanStatusMessage(isKo ? '선택한 학급 커리큘럼 항목이 성공적으로 적용되었습니다!' : 'Selected items successfully applied to your weekly curriculum!');
  };

  const loadCurriculum = async () => {
    const targetClass = selectedClass || fallbackDemoClass;
    setIsLoadingCurriculum(true);
    const currDocId = `${targetClass.id}_week_${targetClass.activeWeekNumber || 1}`;
    const localKey = `curriculum_${currDocId}`;
    latestCurriculumRequestId.current = currDocId;

    // 1. Pre-load from LocalStorage for instant render & offline compatibility
    try {
      const cached = localStorage.getItem(localKey);
      if (cached) {
        const data = JSON.parse(cached);
        setCurriculumTopic(asString(data.topic));
        setCurriculumVocab(asJoinedString(data.vocabWords));
        setCurriculumPhonics(asJoinedString(data.phonicsRules));
        setCurriculumPassage(asString(data.passage));
        setCurriculumOther(asString(data.other));
        setCurriculumAnswerKey(Array.isArray(data.answerKey) ? data.answerKey : []);
        setCurriculumLastEditedByName(asString(data.lastEditedByName));
        setCurriculumLastEditedAt(asString(data.lastEditedAt));
      } else {
        setCurriculumTopic('');
        setCurriculumVocab('');
        setCurriculumPhonics('');
        setCurriculumPassage('');
        setCurriculumOther('');
        setCurriculumAnswerKey([]);
        setCurriculumLastEditedByName('');
        setCurriculumLastEditedAt('');
      }
    } catch (e) {
      console.warn('LocalStorage curriculum load error:', e);
    }

    // 2. Fetch latest snapshot from Firestore — skip for the demo/no-class
    // placeholder, its doc is never created server-side so this would only
    // ever produce a permission-denied console error, not real data.
    if (targetClass.isDemo) {
      setIsLoadingCurriculum(false);
      return;
    }
    try {
      const docRef = doc(dbInstance, 'curriculums', currDocId);
      const snap = await getDoc(docRef);
      // A newer loadCurriculum() call (selectedClass switched again while
      // this one was in flight) has already claimed the ref — this response
      // is stale, drop it instead of overwriting the newer class's fields.
      if (latestCurriculumRequestId.current !== currDocId) return;
      if (snap.exists()) {
        const data = snap.data();
        setCurriculumTopic(asString(data.topic));
        setCurriculumVocab(asJoinedString(data.vocabWords));
        setCurriculumPhonics(asJoinedString(data.phonicsRules));
        setCurriculumPassage(asString(data.passage));
        setCurriculumOther(asString(data.other));
        setCurriculumAnswerKey(Array.isArray(data.answerKey) ? data.answerKey : []);
        setCurriculumLastEditedByName(asString(data.lastEditedByName));
        setCurriculumLastEditedAt(asString(data.lastEditedAt));
        try {
          localStorage.setItem(localKey, JSON.stringify(data));
        } catch (e) {
          console.warn('Failed to cache curriculum to localStorage:', e);
        }
      }
    } catch (err) {
      console.warn('Failed to load curriculum from Firestore (using local fallback):', err);
      setSyncWarning(
        isKo
          ? '⚠️ 클라우드에서 커리큘럼을 불러오지 못해 이 기기에 저장된 정보를 표시하고 있습니다.'
          : "⚠️ Couldn't load curriculum from the cloud — showing what's saved on this device."
      );
    } finally {
      setIsLoadingCurriculum(false);
    }
  };

  const handleSaveCurriculum = async (e: React.FormEvent) => {
    e.preventDefault();
    const targetClass = selectedClass || fallbackDemoClass;

    // --- GUARDRAIL VALIDATION FOR "OTHER" FIELD ---
    const guardrailResult = validateCurriculumOtherField(curriculumOther);
    if (!guardrailResult.ok) {
      showToast({ type: 'error', message: isKo
        ? `[보안 경고] 부적절한 단어("${guardrailResult.badWord}")가 포함되어 있습니다. 학습에 적합한 언어를 사용해 주세요.`
        : `[Security Warning] Inappropriate term detected ("${guardrailResult.badWord}"). Please use appropriate educational content.`
      });
      return;
    }

    setIsSavingCurriculum(true);
    const currDocId = `${targetClass.id}_week_${targetClass.activeWeekNumber || 1}`;
    const localKey = `curriculum_${currDocId}`;

    try {
      const vocabList = curriculumVocab.split(/[,\n]/).map(s => s.trim()).filter(Boolean);
      const phonicsList = curriculumPhonics.split(/[,\n]/).map(s => s.trim()).filter(Boolean);

      // Multiple FTs can share a class (assignedTeacherUids), so a save here
      // silently overwrites whatever a co-teacher last wrote with no trace
      // of who or when — this stamps both so a conflict is at least visible
      // after the fact, not a lock (Audit: no lock/attribution on shared
      // curriculum edits).
      const editedByName = user?.name || user?.email || 'Unknown teacher';
      const editedAt = new Date().toISOString();
      const payload = {
        classId: targetClass.id,
        teacherUid: user?.uid || targetClass.teacherUid || '',
        weekNumber: targetClass.activeWeekNumber || 1,
        topic: curriculumTopic.trim(),
        vocabWords: vocabList,
        phonicsRules: phonicsList,
        passage: curriculumPassage.trim(),
        other: curriculumOther.trim(),
        answerKey: curriculumAnswerKey,
        updatedAt: editedAt,
        lastEditedByUid: user?.uid || '',
        lastEditedByName: editedByName,
        lastEditedAt: editedAt,
      };

      // 1. Dual-persist to local storage immediately
      try {
        localStorage.setItem(localKey, JSON.stringify(payload));
      } catch (lErr) {
        console.warn('LocalStorage write warning:', lErr);
      }

      // 2. Persist to Firestore
      let curriculumFirestoreFailed = false;
      try {
        const docRef = doc(dbInstance, 'curriculums', currDocId);
        await setDoc(docRef, payload, { merge: true });
      } catch (firestoreErr) {
        console.warn('Firestore curriculum write warning (saved locally):', firestoreErr);
        curriculumFirestoreFailed = true;
      }

      setCurriculumLastEditedByName(editedByName);
      setCurriculumLastEditedAt(editedAt);

      if (curriculumFirestoreFailed) {
        setSyncWarning(
          isKo
            ? '⚠️ 커리큘럼이 이 기기에만 저장되었습니다. 클라우드에 동기화되지 않았습니다.'
            : '⚠️ Curriculum saved on this device only — it has not synced to the cloud yet.'
        );
      } else {
        showToast({ type: 'success', message: isKo ? '주간 커리큘럼이 성공적으로 저장되었습니다!' : 'Weekly curriculum saved successfully!' });
      }
    } catch (err) {
      console.error('Failed to save curriculum:', err);
      showToast({ type: 'error', message: isKo ? '저장 실패. 다시 시도해 주세요.' : 'Failed to save curriculum.' });
    } finally {
      setIsSavingCurriculum(false);
    }
  };

  const escapeHtml = (s: string) =>
    String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] as string));

  // Worksheet Format & Question Style State — only ever read by
  // handleGenerateWorksheet and CurriculumEditorForm, so it lives here
  // alongside the rest of the worksheet-generation bucket even though it
  // wasn't part of the original "Curriculum state" comment block.
  const [worksheetType, setWorksheetType] = useState<string>('daily_homework');
  const [questionStyle, setQuestionStyle] = useState<string>('multiple_choice');

  const handleGenerateWorksheet = async () => {
    const vocabList = curriculumVocab.split(/[,\n]/).map(s => s.trim()).filter(Boolean);
    const phonicsList = curriculumPhonics.split(/[,\n]/).map(s => s.trim()).filter(Boolean);

    if (!curriculumTopic.trim() && vocabList.length === 0 && phonicsList.length === 0 && !curriculumPassage.trim()) {
      showToast({
        type: 'error',
        message: isKo
          ? '워크시트를 생성하려면 먼저 주제, 어휘, 파닉스 규칙 또는 지문 중 하나를 입력해 주세요.'
          : 'Set a topic, vocabulary, phonics rules, or passage for this week before generating a worksheet.',
      });
      return;
    }

    setIsGeneratingWorksheet(true);
    try {
      const idToken = await auth.currentUser?.getIdToken();
      const res = await fetch('/api/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${idToken}` },
        body: JSON.stringify({
          task: 'generate_worksheet',
          worksheetType,
          questionStyle,
          language: isKo ? 'ko' : 'en',
          curriculum: {
            topic: curriculumTopic.trim(),
            vocabWords: vocabList,
            phonicsRules: phonicsList,
            passage: curriculumPassage.trim(),
          },
        }),
      });

      if (!res.ok) {
        const errBody = await res.json().catch(() => ({}));
        throw new Error(errBody?.error || `HTTP_${res.status}`);
      }

      const { worksheet } = await res.json();
      if (!worksheet?.questions?.length) throw new Error('EMPTY_WORKSHEET');

      const title = isKo ? worksheet.title_ko || worksheet.title_en : worksheet.title_en || worksheet.title_ko;
      const instructions = isKo ? worksheet.instructions_ko : worksheet.instructions_en;

      const questionsHtml = worksheet.questions.map((q: any) => {
        const prompt = isKo ? (q.prompt_ko || q.prompt_en) : (q.prompt_en || q.prompt_ko);
        const choicesHtml = Array.isArray(q.choices) && q.choices.length > 0
          ? `<div class="choices">${q.choices.map((c: string) => `<div>${escapeHtml(c)}</div>`).join('')}</div>`
          : '<div class="answer-line"></div>';
        return `<div class="question"><span class="qnum">${q.number}.</span> ${escapeHtml(prompt)}${choicesHtml}</div>`;
      }).join('');

      const answerKeyHtml = worksheet.questions.map((q: any) =>
        `<div class="answer-row"><span class="qnum">${q.number}.</span> ${escapeHtml(q.answer)}</div>`
      ).join('');

      const printWindow = window.open('', '_blank');
      if (!printWindow) {
        showToast({ type: 'error', message: isKo ? '팝업이 차단되었습니다. 팝업 차단을 해제해 주세요.' : 'Pop-up blocked — please allow pop-ups to print the worksheet.' });
        return;
      }

      printWindow.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"><title>${escapeHtml(title || 'Worksheet')}</title>
<style>
body { font-family: 'Helvetica Neue', Arial, sans-serif; padding: 40px; color: #111; }
h1 { font-size: 22px; margin-bottom: 4px; }
.instructions { color: #555; font-size: 13px; margin-bottom: 24px; }
.question { margin-bottom: 18px; font-size: 14px; line-height: 1.6; }
.qnum { font-weight: bold; margin-right: 6px; }
.choices { margin-top: 6px; margin-left: 20px; display: flex; flex-direction: column; gap: 4px; font-size: 13px; }
.answer-line { border-bottom: 1px solid #999; height: 24px; margin-top: 6px; margin-left: 20px; max-width: 320px; }
.answer-key { page-break-before: always; margin-top: 40px; }
.answer-row { font-size: 13px; margin-bottom: 6px; }
</style></head><body>
<h1>${escapeHtml(title || 'Worksheet')}</h1>
${instructions ? `<p class="instructions">${escapeHtml(instructions)}</p>` : ''}
${questionsHtml}
<div class="answer-key"><h2>${isKo ? '정답지 (교사용)' : 'Answer Key (Teacher Copy)'}</h2>${answerKeyHtml}</div>
</body></html>`);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => printWindow.print(), 300);

      showToast({ type: 'success', message: isKo ? '⚡ AI 맞춤 워크시트(PDF)가 생성되었습니다!' : '⚡ AI Worksheet Generated Successfully!' });
    } catch (err: any) {
      console.error('Worksheet generation failed:', err);
      const message = err?.message === 'GENERATE_LIMIT_REACHED'
        ? (isKo ? '오늘의 생성 한도에 도달했습니다.' : "You've reached today's generation limit.")
        : (isKo ? '워크시트 생성에 실패했습니다. 다시 시도해 주세요.' : 'Failed to generate worksheet. Please try again.');
      showToast({ type: 'error', message });
    } finally {
      setIsGeneratingWorksheet(false);
    }
  };

  return {
    selectedTextbookName, setSelectedTextbookName,
    curriculumTopic, setCurriculumTopic,
    curriculumVocab, setCurriculumVocab,
    curriculumPhonics, setCurriculumPhonics,
    curriculumPassage, setCurriculumPassage,
    curriculumOther, setCurriculumOther,
    curriculumAnswerKey, setCurriculumAnswerKey,
    curriculumLastEditedByName, setCurriculumLastEditedByName,
    curriculumLastEditedAt, setCurriculumLastEditedAt,
    curriculumSlideIndex, setCurriculumSlideIndex,
    isLoadingCurriculum, isSavingCurriculum, isGeneratingWorksheet,
    isDraggingFile, setIsDraggingFile,
    isScanningTextbook,
    textbookPreviewUrl, textbookPreviewUrls,
    showScannedModal, setShowScannedModal,
    scannedData, setScannedData,
    uploadedFileType, uploadedFileName,
    selectedPageIndex, setSelectedPageIndex,
    pendingScanFiles,
    handleStageFiles, handleRemoveStagedFile, clearStagedFiles, handleScanStagedFiles,
    syllabusFileName, syllabusPreviewUrl, syllabusScannedData,
    syllabusWeeks, isScanningSyllabus, syllabusWeeklySchedule,
    handleSyllabusWeeksChange,
    worksheetFileName, worksheetPreviewUrl, worksheetScannedData,
    setWorksheetPreviewUrl, setWorksheetScannedData, setWorksheetFileName,
    isScanningWorksheet,
    activeScannedModalType, setActiveScannedModalType,
    selectedScannedTopic, setSelectedScannedTopic,
    selectedScannedPassage, setSelectedScannedPassage,
    selectedScannedOther, setSelectedScannedOther,
    selectedScannedVocab, setSelectedScannedVocab,
    selectedScannedPhonics, setSelectedScannedPhonics,
    activeScannedTab, setActiveScannedTab,
    scanStatusMessage,
    showDocPreviewModal, setShowDocPreviewModal,
    docPreviewUrl, setDocPreviewUrl,
    newVocabInput, setNewVocabInput,
    newPhonicsInput, setNewPhonicsInput,
    handleAddVocabWord, handleRemoveVocabWord,
    handleAddPhonicsRule, handleRemovePhonicsRule,
    handleRemoveAnswerKeyEntry, handleEditAnswerKeyEntry,
    handleTextbookFileUpload,
    applyScannedSelectionToCurriculum,
    loadCurriculum, handleSaveCurriculum,
    worksheetType, setWorksheetType,
    questionStyle, setQuestionStyle,
    handleGenerateWorksheet,
  };
}
